name: Build Latest Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - "docs/**"
  workflow_dispatch:
jobs:
  publish-latest-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/openai-scf-proxy:latest .
      - name: Publish image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/openai-scf-proxy:latest